config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :recipes_preview
  resources :full_recipe
  resources :stashes, only: [:index, :show, :create, :destroy]
end

app/models/full_recipe.rb
class FullRecipe

  def initialize(recipe_id)
    @recipe_id = recipe_id
  end

  def recipe_content
    response = Faraday.get(
      "http://api.yummly.com/v1/api/recipe/#{@recipe_id}",
      :_app_id => ENV['YUMMLY_ID'],
      :_app_key => ENV['YUMMLY_KEY'],
    )

    json_data = JSON.parse(response.body)
    large_photo = json_data["images"].map { |images| images["imageUrlsBySize"]["360"] }.first
    small_photo = json_data["images"].map { |images| images["imageUrlsBySize"]["90"] }.first
    ingredient_quantities = json_data["ingredientLines"].uniq
    rating = json_data["rating"]
    name = json_data["name"]
    yielding = json_data["yield"]
    recipe_url = json_data["source"]["sourceRecipeUrl"]
    RecipeFull.new(:name => name,
                             :large_photo => large_photo,
                             :small_photo => small_photo,
                             :yielding => yielding,
                             :rating => rating,
                             :ingredient_quantities => ingredient_quantities,
                             :recipe_url => recipe_url)
  end
end

app/models/recipe.rb
class Recipe
  attr_reader :name, :recipe_id, :image_url, :ingredients

  def initialize(attributes)
    @name, @recipe_id, @image_url, @ingredients = attributes.values_at(
      :name, :recipe_id, :image_url, :ingredients
    )
  end
end

app/models/recipe_full.rb
class RecipeFull
  attr_reader :name, :large_photo, :small_photo, :rating, :yielding, :recipe_url, :ingredient_quantities

  def initialize(attributes)
    @name, @large_photo, @small_photo, @rating, @yielding, @recipe_url, @ingredient_quantities = attributes.values_at(
      :name, :large_photo, :small_photo, :rating, :yielding, :recipe_url, :ingredient_quantities
    )
  end
end

app/models/recipe_preview.rb
class RecipePreview

  def initialize(ingredients)
    @ingredients = ingredients.reject(&:empty?).map(&:downcase)
  end

  def results
    response = Faraday.get(
      "http://api.yummly.com/v1/api/recipes",
      :_app_id => ENV['YUMMLY_ID'],
      :_app_key => ENV['YUMMLY_KEY'],
      :allowedIngredient => @ingredients
    )
    json_data = JSON.parse(response.body)
    recipes = json_data["matches"]
    output = []
    recipes.each do |recipe_hash|
      recipe_name = recipe_hash["recipeName"]
      id = recipe_hash["id"]
      image_url = recipe_hash.fetch("imageUrlsBySize", {})["90"]
      ingredients = recipe_hash["ingredients"]
      output << Recipe.new(:name => recipe_name,
                           :recipe_id => id, :image_url => image_url,
                           :ingredients => ingredients)


    end
    output
  end
end

app/models/stash.rb
class Stash < ActiveRecord::Base
  belongs_to :user
  serialize :ingredients, JSON
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :stashes

  validates_uniqueness_of :email
  validates_presence_of :email

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception


  def ensure_current_user
    redirect_to root_path unless current_user
  end

  helper_method :current_user

  private

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      nil
    end

  end

end

app/controllers/full_recipe_controller.rb
class FullRecipeController < ApplicationController

  before_action :ensure_current_user

  def show
    @id = params[:id]
  end

  private

  def full_recipe
    @full_recipe ||= FullRecipe.new(params[:id]).recipe_content
  end

  helper_method :full_recipe
end

app/controllers/recipes_preview_controller.rb
class RecipesPreviewController < ApplicationController

  before_action :ensure_current_user

  def index
  end

  def new
  end

  def create
    if recipe_preview.results.empty?
      flash.now[:no_results] = "Please check your spelling or choose different ingredients"
      render :new
    else
      render :create
    end
  end

  alias_method :index, :create

  private

  def recipe_preview
    @recipe_preview ||= if params[:ingredients]
                          session[:last_search] = params[:ingredients]
                          RecipePreview.new(params[:ingredients])
                        else
                          RecipePreview.new(session[:last_search])
                        end
  end

  helper_method :recipe_preview

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by email: params[:user][:email]
    if @user.present? && @user.authenticate(params[:user][:password])
      session[:user_id] = @user[:id]
      flash[:success] = "Welcome, #{@user[:email]}"
      redirect_to root_path
    else
      @user = User.new
      flash[:error] = 'Incorrect Email or Password'
      render new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/stashes_controller.rb
class StashesController < ApplicationController

  before_action :ensure_current_user

  respond_to :html, :json

  def index
    @stashes = current_user.stashes
    respond_with @stashes
  end

  def show
    @stash = current_user.stashes.find_by_yummly_id(params[:id])
    respond_with stash: @stash
  end

  def create
    @stash = current_user.stashes.create(stash_params)
    render json: {
      stash: @stash, count: current_user.stashes.count
    }
  end

  def destroy
    @stash = current_user.stashes.find_by_yummly_id(params[:id])
    @stash.destroy
    render json: {
      stash: @stash, count: current_user.stashes.count
    }, status: :ok
  end

  private
  def stash_params
    params.require(:stash).permit(:name, :yummly_id, :photo_url, :recipe_url, :ingredients => [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(email: params[:user][:email], password: params[:user][:password])
    if @user.save
      redirect_to new_session_path, notice: "Registered! Please login now"
    else
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/full_recipe/_full_recipe.html.erb
<h4><%= link_to "Back to Search Results", recipes_preview_index_path, class: "back_to_results" %></h4>
<h1><%= full_recipe.name %></h1>
<% unless full_recipe.large_photo.match(/\b(null)\b/i) %>
  <%= image_tag full_recipe.large_photo, class: "large_photo" %>
<% end %>

<div class="stash_it_button"><%= link_to "Stash It", stashes_path(format: :json), class: "action-button shadow animate red",
                                         data: {name: full_recipe.name, yummly_id: params[:id],
                                                photo_url: full_recipe.small_photo, full_recipe_url: full_recipe.recipe_url,
                                                ingredients: full_recipe.ingredient_quantities} %>
</div>
<div class="trash_it_button"><%= link_to "Trash It", stash_path(params[:id], format: :json), class: "action-button shadow animate orange-trash" %></div>
<div class="recipe-contents-container">
  <% if full_recipe.yielding.present? %>
    <h5>Yields: <%= full_recipe.yielding %> <br>Rating: <%= full_recipe.rating %> </h5>
  <% end %>
  <ul>
    <h4>Ingredients</h4>
    <% full_recipe.ingredient_quantities.each do |ingredient| %>
      <li><%= ingredient %></li>
    <% end %>
  </ul>
  <%= link_to "Visit the source of this recipe", full_recipe.recipe_url, class: "action-button shadow animate orange", target: :_blank %>
</div>

<script>
  $(function () {
    setupStash('<%= stash_path(params[:id], format: :json) %>');
  });
</script>

app/views/full_recipe/show.html.erb
<%= link_to "New Search", new_recipes_preview_path, class: "action-button shadow animate blue" %>

<div class="opaque full-show">
    <%= render partial: 'full_recipe/full_recipe', object: full_recipe %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>RecipeStash</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,300,100&subset=latin,latin-ext">
  <link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>

</div>
<% if current_user %>
    <%= link_to 'Logout', "/sessions/#{current_user.id}", method: :delete, class: "action-button shadow animate red logout"  %>
  <div class="stash_link">
    <%= link_to "See my Stash", stashes_path, class: "action-button shadow animate green",
          style: current_user.stashes.any? ? '' : 'display: none' %>
  </div>
  <% end %>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/index.html.erb
<h1>Here are your search results for </h1>
<% @recipes.each do |recipe| %>
<%= recipe.ingredient1 %>,
<%= recipe.ingredient2 %>,
<%= recipe.ingredient3 %>,
<%= recipe.ingredient4 %>,
<%= recipe.ingredient5 %>

<% end %>

app/views/recipes/new.html.erb
<h1>Add Your Ingredients Below</h1>

<%= form_tag :recipe, controller: "recipes", action: "create", method: "get" %>
  <%= text_field_tag :ingredient1 %>
  <%= text_field_tag :ingredient2 %>
  <%= text_field_tag :ingredient3 %>
  <%= submit_tag('Submit') %>

app/views/recipes_preview/_recipe_preview.html.erb
<ul>
  <li><h3><%= recipe.name %></h3>
    <br><%= image_tag recipe.image_url %><%= link_to "See Full Recipe", full_recipe_path(recipe.recipe_id), class: "action-button shadow animate red" %>
    <ul>
      <% recipe.ingredients.each do |ingredient| %>
        <li><%= ingredient %></li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/recipes_preview/create.html.erb
<%= link_to "New Search", new_recipes_preview_path, class: "action-button shadow animate blue" %>

<div class="opaque">
  <%= link_to(image_tag("RecipeStashLogo.png", class: "logo"), new_recipes_preview_path) %>
  <div class="forms">
    <h1>Based on Your Ingredients..</h1>
  </div>

  <div class="previews">
    <%= render partial: 'recipes_preview/recipe_preview', collection: recipe_preview.results, as: :recipe %>
  </div>
</div>

app/views/recipes_preview/new.html.erb
<div class="opaque">
  <div class="error">
  <%= flash[:no_results] %>
  </div>
  <%= link_to(image_tag("RecipeStashLogo.png", class: "logo"), root_path) %>
  <div class="forms_with_errors">
    <h1>Fill In Your Ingredients Below</h1>

    <%= form_tag '/recipes_preview', method: :post do %>
      <%= text_field_tag 'ingredients[]', nil, placeholder: "First Ingredient" %>
      <%= text_field_tag 'ingredients[]', nil, placeholder: "Second Ingredient" %>
      <%= text_field_tag 'ingredients[]', nil, placeholder: "Third Ingredient" %>

      <%= submit_tag('Submit') %>
    <% end %>
  </div>
</div>

app/views/stashes/_stash_list.html.erb
<div class="recipe_bucket">
  <h2><%= stash.name %></h2>

  <div class="buttons1"><%= link_to "Visit this recipe", stash.recipe_url, class: "btn2", target: :_blank %></div>

  <div>
    <% unless stash.photo_url.match(/\b(null)\b/i) %>
      <%= image_tag stash.photo_url %>
    <% end %>
  </div>
  <ul>
    <% stash.ingredients.each do |ingredient| %>
      <li class="stash_list"><%= ingredient %></li>
    <% end %>
  </ul>
  <strong><%= link_to "Trash It", stash_path(stash.yummly_id), class: "remove" %></strong></br>
</div>

app/views/stashes/index.html.erb
<%= link_to "New Search", new_recipes_preview_path, class: "action-button shadow animate blue" %>


<div class="gray-opaque">
  <div class="wrap">


    <header>
      <p><%= link_to "The Stash", root_path, class: "stash" %></p>
      <h3><%= link_to "Back to Search Results", recipes_preview_index_path, class: "back_to_results2" %></h3>

    </header>
  </div>

    <div id="book">
      <div id="bookFront"></div>
      <div id="bookBack"></div>
      <div id="paper">
        <div id="lines"></div>
      </div>
    </div>

    <%= render partial: 'stashes/stash_list', collection: @stashes, as: :stash %>

</div>

<script>
  $(removeStash)
</script>

app/views/users/new.html.erb
<div class="opaque">
  <%= link_to(image_tag("RecipeStashLogo.png", class: "logo"), root_path) %>
  <% if @user.errors.any? %>
    <div class="error">
      <% @user.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
    </div>
  <% end %>
  <div class="forms_with_errors">
    <h1>Register Below Please..</h1>
    <%= form_for @user, :url => {:action => 'create'} do |f| %>
      <table>
        <tr>
          <td><%= f.label :email %></td>
          <td><%= f.text_field :email %></td>
        </tr>
        <tr>
          <td><%= f.label :password %></td>
          <td><%= f.password_field :password %></td>
        </tr>
        <tr>
          <td class=""><%= f.submit "Sign Up" %></td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
  <div class="welcome-wrapper">
    <div class="welcome">
      <strong class="flash"><% if current_user.present? %>
        <%= flash[:success] %></strong>
      <% end %>
      <div class="message">
        <div class="right"><strong>STARING INTO THIS WHEN TRYING TO PLAN A MEAL</strong></div>
        <h1>CAN BE DAUNTING</h1>
        <div class="right"><strong>LUCKILY <span> RECIPESTASH </span>GIVES YOU THE ABILITY TO SEARCH FOR RECIPES BASED
          ON INGREDIENTS THAT YOU ALREADY HAVE IN YOUR FRIDGE OR PANTRY
          </strong></div>
        <% if current_user %>
          </br>
          <%= link_to 'Search For Recipes Now', new_recipes_preview_path, class: "action-button shadow animate red" %>
          <% else %>
          </br>
          <%= link_to 'Register', new_user_path, class: "action-button shadow animate red" %>
          <%= link_to 'Login', new_session_path, class: "action-button shadow animate red"%>
      <% end %>
      </div>
    </div>
  </div>